---
follow_instructions:
  type: chat
  opts:
    strategy: replace
    params:
      model: gpt-4
      max_tokens: 2048
      stop:
        - '```'
    template: >
      Rewrite the following code in accordance with the TODO comments in it.


      Existing code:
      ```{{filetype}}
      {{input}}
      ```


      Rewritten code:
      ```{{filetype}}
add_mocha_tests:
  type: chat
  opts:
    strategy: append
    params:
      model: gpt-4
      max_tokens: 2048
      stop:
        - '```'
    template: >
      Implement Mocha tests for the following code.


      Code:
      ```{{filetype}}
      {{input}}
      ```


      Tests:
      ```{{filetype}}
comments:
  type: chat
  opts:
    strategy: replace
    params:
      model: gpt-4
      max_tokens: 2048
      stop:
        - '```'
    template: >
      Add comments to the following code. The comments should explain 'why'
      rather than 'how'.


      Existing code:
      ```{{filetype}}
      {{input}}
      ```


      Rewritten code:
      ```{{filetype}}
