#!/usr/bin/env bash

# Update dotfile symlinks
rcup

# Construct SSH config using files in ~/.ssh/config.d
# load-ssh - temporarily disabled

# Delete dead symlinks in Scripts directory
find ~/Scripts -xtype l -delete

# GnuPG permissions
if [[ -d ~/.gnupg ]]; then
    chmod 700 $(realpath ~/.gnupg)
    find -L ~/.gnupg -type f -regex '.+\.\(conf\|key\|gpg.?\)' -exec realpath {} \; -exec chmod 600 {} \; > /dev/null
fi

# SSH permissions
chmod 700 $(realpath ~/.ssh)
find -L ~/.ssh -type f -name 'id_rsa*' -exec realpath {} \; -exec chmod 600 {} \; > /dev/null

# Update desktop database
update-desktop-database ~/.local/share/applications/
