#!/usr/bin/env bash

export PATH="$HOME/.local/bin:$PATH"

npm_packages="$HOME/.npm-packages"
if [ -d "$npm_packages" ] && [[ "$:PATH:" != *":$PATH:"* ]]; then
  export PATH="$npm_packages/bin:$PATH"
fi
