#!/usr/bin/env bash

export EDITOR=nvim
export VISUAL=nvim

export NPM_PACKAGES="$HOME/.npm-packages"

# Add NPM packages bin directory to the path if it's missing
npm_bin="$NPM_PACKAGES/bin"
if [ -d "$npm_bin" ] && [[ ":$PATH:" != *":$npm_bin:"* ]]; then
  export PATH="$npm_bin${PATH:+":$PATH"}"
fi

# Add personal bin directory to the path if it's missing
local_bin="$HOME/.local/bin"
if [ -d "$local_bin" ] && [[ ":$PATH:" != *":$local_bin:"* ]]; then
  export PATH="$local_bin${PATH:+":$PATH"}"
fi
